Contrast for pagination focus outlines
code4lib/2022.code4lib.org pull request #160
Opened 2022-03-23 21:14 UTC by kaitlinnewson

Improve the contrast for both the schedule pagination and workshop time pagination outlines. Also adds the schedule pagination to the workshop page for easier transition between the schedule pages. 

To test, navigate through the workshop and schedule pages with keyboard tabbing and test the contrast between the focus outline and the background of that page and button colours.

Resolves #152.

2022-03-24 17:36 UTC, phette23 commented
Sorry that commit was just the wrong number, I force-pushed to overwrite it so you'll see it's orphaned now.

Is there a way to test numerical contrast ratios? The contrast looks great but I wasn't sure if you wanted to test with a particular tool. The accessibility check in Chrome dev tools doesn't check focus/hover I think.

2022-03-24 18:23 UTC, kaitlinnewson commented
> Is there a way to test numerical contrast ratios? The contrast looks great but I wasn't sure if you wanted to test with a particular tool. The accessibility check in Chrome dev tools doesn't check focus/hover I think.

I used this tool to check the contrast individually: https://www.tpgi.com/color-contrast-checker/

2022-03-24 18:29 UTC, phette23 requested changes
See my comments: I think we should make pagination and workshop sorting work the same, and I wonder if `day: day0` makes more sense for the workshops index than `day: day5`.

Also I noticed that the middle "AM" sort-workshop-time button does not have a right border when focused:
<img width="162" alt="Screen Shot 2022-03-24 at 11 24 18 AM" src="https://user-images.githubusercontent.com/1024833/159985896-c0cb0459-564d-4de3-8d48-df316e5ba683.png">

2022-03-24 18:29 UTC, phette23 commented on assets/_scss/_presentations-workshops.scss
> +      background-color: $accent;
The pagination menu and the workshop sorting one function differently in terms of their background colors and selection state. Pagination: selected element has accent bg, focused element has border, other elements have neither. Workshop sorting: selected element has a light gray bg, focused element has border _and accent bg_, other elements have neither.

Would it makes sense to have both operate the same? I like the way pagination works if given a choice between the two, I think having the accent color bg is much clearer than a gray bg that can be confused with some sort of "inactive" state.

2022-03-24 18:33 UTC, kaitlinnewson commented on workshops/index.html
> +day: day5
Yes, this is a holdover from last year. What do you think about using `day0`? Or I could change it to `day1` and adjust the other pages.

2022-03-24 18:34 UTC, phette23 commented on workshops/index.html
> +day: day5
I was thinking `day0` makes the most sense, I like how it kind of sets the pre-conferences apart from the main conference days and makes the references elsewhere logical (first day is day1, etc.). Thanks!

2022-03-25 15:52 UTC, kaitlinnewson commented
@phette23 this is ready for a second review now

2022-03-25 17:11 UTC, phette23 approved these changes
Awesome! This looks so much better.

2022-03-25 17:11 UTC, merged